package com.xx.jaseatschoicejava.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.xx.jaseatschoicejava.dto.HotTopicResponse;
import com.xx.jaseatschoicejava.entity.HotTopic;
import com.xx.jaseatschoicejava.entity.Tutorial;
import com.xx.jaseatschoicejava.mapper.HotTopicMapper;
import com.xx.jaseatschoicejava.mapper.TutorialMapper;
import com.xx.jaseatschoicejava.service.HotTopicService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 今日热点服务实现类
 * 实现组合策略获取热点数据
 */
@Service
public class HotTopicServiceImpl extends ServiceImpl<HotTopicMapper, HotTopic> implements HotTopicService {

    private static final Logger log = LoggerFactory.getLogger(HotTopicServiceImpl.class);

    @Autowired
    private HotTopicMapper hotTopicMapper;

    @Autowired
    private TutorialMapper tutorialMapper;

    @Autowired
    private RestTemplate restTemplate;

    @Value("${hot-topic.api.url:}")
    private String thirdPartyApiUrl;

    @Value("${hot-topic.api.enabled:false}")
    private boolean thirdPartyApiEnabled;

    /**
     * 获取今日热点（组合策略）
     * 优先级：数据库配置 > 热门教程 > AI生成 > 默认热点
     */
    @Override
    public HotTopicResponse getTodayHotTopic() {
        log.info("开始获取今日热点...");

        // 1. 优先从数据库查询当前生效的热点
        HotTopic dbHotTopic = getActiveFromDatabase();
        if (dbHotTopic != null) {
            log.info("从数据库获取热点: {}", dbHotTopic.getContent());

            // 构建响应对象
            HotTopicResponse response = new HotTopicResponse();
            response.setContent(dbHotTopic.getContent());
            response.setSourceType(dbHotTopic.getSourceType());
            response.setSourceId(dbHotTopic.getSourceId());

            // 根据来源类型设置是否可点击
            if ("TUTORIAL".equals(dbHotTopic.getSourceType()) && dbHotTopic.getSourceId() != null) {
                response.setRedirectUrl("/user/home/tutorials/" + dbHotTopic.getSourceId());
                response.setClickable(true);
            } else if (dbHotTopic.getRemark() != null && dbHotTopic.getRemark().startsWith("http")) {
                response.setRedirectUrl(dbHotTopic.getRemark());
                response.setClickable(true);
            } else {
                response.setClickable(false);
            }

            response.setCreateTime(dbHotTopic.getCreateTime());
            return response;
        }

        // 2. 从热门教程提取
        Tutorial hottestTutorial = getHottestTutorial();
        if (hottestTutorial != null) {
            String title = hottestTutorial.getTitle();
            if (title != null && title.length() > 30) {
                title = title.substring(0, 27) + "...";
            }

            log.info("从教程提取热点: {}", title);

            // 自动保存到数据库
            saveAutoGeneratedTopic(title, HotTopic.SourceType.TUTORIAL, hottestTutorial.getId());

            // 返回可点击的教程热点
            return HotTopicResponse.fromTutorial(title, hottestTutorial.getId());
        }

        // 3. AI生成热点
        String aiTopic = generateAITopic();
        if (aiTopic != null) {
            log.info("AI生成热点: {}", aiTopic);
            // 自动保存到数据库
            saveAutoGeneratedTopic(aiTopic, HotTopic.SourceType.AI, null);
            // 返回不可点击的AI热点
            return HotTopicResponse.fromAI(aiTopic);
        }

        // 4. 第三方API（备选方案）
        if (thirdPartyApiEnabled) {
            String apiTopic = fetchFromThirdPartyAPI();
            if (apiTopic != null) {
                log.info("从第三方API获取热点: {}", apiTopic);
                // 自动保存到数据库
                saveAutoGeneratedTopic(apiTopic, HotTopic.SourceType.API, null);
                // 返回不可点击的API热点
                return HotTopicResponse.fromAI(apiTopic);
            }
        }

        // 5. 默认热点
        String defaultTopic = getDefaultHotTopic();
        log.info("使用默认热点: {}", defaultTopic);
        return HotTopicResponse.fromAI(defaultTopic);
    }

    /**
     * 从数据库查询当前生效的热点
     */
    @Override
    public HotTopic getActiveFromDatabase() {
        try {
            LocalDateTime now = LocalDateTime.now();
            HotTopic hotTopic = hotTopicMapper.selectActiveHotTopic(now);
            if (hotTopic != null && hotTopic.isActive()) {
                return hotTopic;
            }
        } catch (Exception e) {
            log.error("从数据库查询热点失败", e);
        }
        return null;
    }

    /**
     * 获取最热门的教程（辅助方法）
     */
    private Tutorial getHottestTutorial() {
        try {
            return tutorialMapper.selectHottestTutorial();
        } catch (Exception e) {
            log.error("获取最热门教程失败", e);
            return null;
        }
    }

    /**
     * AI生成热点（辅助方法）
     */
    private String generateAITopic() {
        try {
            LocalDateTime now = LocalDateTime.now();
            int month = now.getMonthValue();
            int hour = now.getHour();

            // 根据月份和时段生成不同的热点
            String topic = generateTopicBySeasonAndTime(month, hour);
            log.info("AI生成热点内容: {}", topic);
            return topic;
        } catch (Exception e) {
            log.error("AI生成热点失败", e);
            return null;
        }
    }

    /**
     * 获取默认热点
     */
    private String getDefaultHotTopic() {
        return "健康饮食，快乐生活";
    }

    /**
     * 从热门教程提取热点
     */
    @Override
    public String extractFromTutorial() {
        try {
            Tutorial hottestTutorial = tutorialMapper.selectHottestTutorial();
            if (hottestTutorial != null) {
                String title = hottestTutorial.getTitle();
                // 简化标题，去掉过长的部分
                if (title != null && title.length() > 30) {
                    return title.substring(0, 27) + "...";
                }
                return title;
            }
        } catch (Exception e) {
            log.error("从教程提取热点失败", e);
        }
        return null;
    }

    /**
     * AI生成热点内容
     * 基于当前日期、季节等因素生成
     */
    @Override
    public String generateByAI() {
        try {
            LocalDateTime now = LocalDateTime.now();
            int month = now.getMonthValue();
            int hour = now.getHour();

            // 根据月份和时段生成不同的热点
            String topic = generateTopicBySeasonAndTime(month, hour);

            log.info("AI生成热点内容: {}", topic);
            return topic;

        } catch (Exception e) {
            log.error("AI生成热点失败", e);
            return null;
        }
    }

    /**
     * 从第三方API获取热点
     */
    @Override
    public String fetchFromThirdPartyAPI() {
        if (!thirdPartyApiEnabled || thirdPartyApiUrl == null || thirdPartyApiUrl.isEmpty()) {
            log.warn("第三方API未启用或未配置");
            return null;
        }

        try {
            // 示例：调用微博热搜API（需要实际配置API地址和密钥）
            Map<String, Object> response = restTemplate.getForObject(thirdPartyApiUrl, Map.class);

            if (response != null && response.containsKey("hot_topic")) {
                String topic = (String) response.get("hot_topic");
                log.info("从第三方API获取热点成功: {}", topic);
                return topic;
            }
        } catch (Exception e) {
            log.error("从第三方API获取热点失败", e);
        }
        return null;
    }

    /**
     * 根据季节和时段生成热点
     */
    private String generateTopicBySeasonAndTime(int month, int hour) {
        // 季节关键词
        String season = getSeasonKeyword(month);

        // 时段关键词
        String timePeriod = getTimePeriodKeyword(hour);

        // 组合生成热点
        String[] templates = {
                "{季节}{时段}饮食指南",
                "{季节}{时段}健康食谱推荐",
                "{季节}{时段}养生小贴士",
                "{季节}{时段}营养搭配建议",
                "{季节}{时段}美食新吃法"
        };

        // 随机选择一个模板
        int index = (int) (Math.random() * templates.length);
        String template = templates[index];

        return template.replace("{季节}", season).replace("{时段}", timePeriod);
    }

    /**
     * 根据月份获取季节关键词
     */
    private String getSeasonKeyword(int month) {
        if (month >= 3 && month <= 5) {
            return "春季";
        } else if (month >= 6 && month <= 8) {
            return "夏季";
        } else if (month >= 9 && month <= 11) {
            return "秋季";
        } else {
            return "冬季";
        }
    }

    /**
     * 根据小时获取时段关键词
     */
    private String getTimePeriodKeyword(int hour) {
        if (hour >= 5 && hour < 9) {
            return "早餐";
        } else if (hour >= 11 && hour < 14) {
            return "午餐";
        } else if (hour >= 17 && hour < 20) {
            return "晚餐";
        } else {
            return "健康";
        }
    }

    /**
     * 保存自动生成的热点到数据库
     */
    private void saveAutoGeneratedTopic(String content, HotTopic.SourceType sourceType, String sourceId) {
        try {
            HotTopic hotTopic = new HotTopic();
            hotTopic.setContent(content);
            hotTopic.setSourceType(sourceType.getCode());
            hotTopic.setSourceId(sourceId); // 保存来源ID（如教程ID）
            hotTopic.setPriority(1); // 自动生成的热点优先级较低
            hotTopic.setStatus(HotTopic.Status.ACTIVE.getCode());
            hotTopic.setStartDate(LocalDateTime.now());
            hotTopic.setEndDate(LocalDateTime.now().plusDays(1)); // 有效期1天
            hotTopic.setRequireReview(false);
            hotTopic.setReviewStatus(HotTopic.ReviewStatus.APPROVED.getCode());

            hotTopicMapper.insert(hotTopic);
            log.info("自动生成的热点已保存到数据库: {}", content);
        } catch (Exception e) {
            log.error("保存自动生成的热点失败", e);
        }
    }

    /**
     * 记录热点点击
     */
    @Override
    @Transactional
    public void recordClick(String content) {
        try {
            // 根据内容查找热点并更新点击次数
            Map<String, Object> params = new HashMap<>();
            params.put("content", content);

            List<HotTopic> topics = hotTopicMapper.selectByMap(params);
            if (!topics.isEmpty()) {
                HotTopic topic = topics.get(0);
                hotTopicMapper.incrementClickCount(topic.getId());
                log.info("记录热点点击: {}", content);
            }
        } catch (Exception e) {
            log.error("记录热点点击失败", e);
        }
    }

    /**
     * 记录热点分享
     */
    @Override
    @Transactional
    public void recordShare(String content) {
        try {
            // 根据内容查找热点并更新分享次数
            Map<String, Object> params = new HashMap<>();
            params.put("content", content);

            List<HotTopic> topics = hotTopicMapper.selectByMap(params);
            if (!topics.isEmpty()) {
                HotTopic topic = topics.get(0);
                hotTopicMapper.incrementShareCount(topic.getId());
                log.info("记录热点分享: {}", content);
            }
        } catch (Exception e) {
            log.error("记录热点分享失败", e);
        }
    }

    /**
     * 创建热点（管理员功能）
     */
    @Override
    @Transactional
    public boolean createHotTopic(HotTopic hotTopic) {
        try {
            hotTopic.setCreateTime(LocalDateTime.now());
            hotTopic.setUpdateTime(LocalDateTime.now());
            return hotTopicMapper.insert(hotTopic) > 0;
        } catch (Exception e) {
            log.error("创建热点失败", e);
            return false;
        }
    }

    /**
     * 更新热点（管理员功能）
     */
    @Override
    @Transactional
    public boolean updateHotTopic(HotTopic hotTopic) {
        try {
            hotTopic.setUpdateTime(LocalDateTime.now());
            return hotTopicMapper.updateById(hotTopic) > 0;
        } catch (Exception e) {
            log.error("更新热点失败", e);
            return false;
        }
    }

    /**
     * 删除热点（管理员功能）
     */
    @Override
    @Transactional
    public boolean deleteHotTopic(String id) {
        try {
            return hotTopicMapper.deleteById(id) > 0;
        } catch (Exception e) {
            log.error("删除热点失败", e);
            return false;
        }
    }

    /**
     * 审核热点（管理员功能）
     */
    @Override
    @Transactional
    public boolean reviewHotTopic(String id, Long reviewerId, boolean approved, String comment) {
        try {
            HotTopic hotTopic = hotTopicMapper.selectById(id);
            if (hotTopic == null) {
                log.warn("热点不存在: {}", id);
                return false;
            }

            hotTopic.setReviewStatus(approved ?
                    HotTopic.ReviewStatus.APPROVED.getCode() :
                    HotTopic.ReviewStatus.REJECTED.getCode());
            hotTopic.setReviewerId(reviewerId);
            hotTopic.setReviewTime(LocalDateTime.now());
            hotTopic.setReviewComment(comment);

            return hotTopicMapper.updateById(hotTopic) > 0;
        } catch (Exception e) {
            log.error("审核热点失败", e);
            return false;
        }
    }
}
