-- 创建退款记录表
CREATE TABLE IF NOT EXISTS `t_refund_record` (
    `refund_id` VARCHAR(64) NOT NULL COMMENT '退款记录ID',
    `refund_no` VARCHAR(64) NOT NULL COMMENT '退款流水号',
    `order_id` BIGINT NOT NULL COMMENT '订单ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '订单号',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `username` VARCHAR(50) COMMENT '用户名',
    `refund_amount` DECIMAL(10, 2) NOT NULL COMMENT '退款金额',
    `reason` VARCHAR(50) COMMENT '退款原因：QUALITY-商品质量问题, DONT_WANT-不想要了, DELAY-配送延迟, OTHER-其他',
    `reason_description` VARCHAR(500) COMMENT '退款原因描述',
    `status` VARCHAR(50) NOT NULL DEFAULT 'PENDING' COMMENT '退款状态：PENDING-待审核, APPROVED-已通过, REJECTED-已拒绝, PROCESSING-处理中, SUCCESS-成功, FAILED-失败',
    `apply_time` DATETIME NOT NULL COMMENT '申请时间',
    `process_time` DATETIME COMMENT '处理时间',
    `audit_by` BIGINT COMMENT '审核人ID',
    `audit_by_name` VARCHAR(50) COMMENT '审核人名称',
    `process_comment` VARCHAR(500) COMMENT '处理备注',
    `refund_method` VARCHAR(50) COMMENT '退款方式：ORIGINAL-原路退回, BALANCE-退回余额',
    `transaction_id` VARCHAR(128) COMMENT '第三方退款流水号',
    `complete_time` DATETIME COMMENT '完成时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`refund_id`),
    UNIQUE KEY `uk_refund_no` (`refund_no`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_apply_time` (`apply_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退款记录表';
