ALTER TABLE t_notification
    MODIFY COLUMN id VARCHAR(64) NOT NULL COMMENT '通知ID',
    MODIFY COLUMN user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    MODIFY COLUMN type VARCHAR(64) NULL DEFAULT 'system' COMMENT '通知类型';
