-- 创建定时任务表
CREATE TABLE IF NOT EXISTS `t_scheduled_task` (
  `id` VARCHAR(64) NOT NULL COMMENT '任务ID',
  `task_name` VARCHAR(255) NOT NULL COMMENT '任务名称',
  `task_code` VARCHAR(100) NOT NULL COMMENT '任务代码',
  `description` TEXT COMMENT '任务描述',
  `cron_expression` VARCHAR(100) COMMENT 'Cron表达式',
  `task_type` VARCHAR(50) NOT NULL COMMENT '任务类型：ONCE-一次性, CRON-Cron表达式, FIXED_RATE-固定频率, FIXED_DELAY-固定延迟',
  `rate_in_millis` BIGINT COMMENT '执行频率（毫秒）',
  `status` VARCHAR(50) NOT NULL DEFAULT 'ENABLED' COMMENT '任务状态：ENABLED-启用, DISABLED-禁用, PAUSED-暂停',
  `task_class_name` VARCHAR(255) COMMENT '任务类名',
  `task_method_name` VARCHAR(100) COMMENT '任务方法名',
  `task_params` TEXT COMMENT '任务参数（JSON格式）',
  `last_execute_time` DATETIME COMMENT '上次执行时间',
  `next_execute_time` DATETIME COMMENT '下次执行时间',
  `execute_count` INT DEFAULT 0 COMMENT '执行次数',
  `fail_count` INT DEFAULT 0 COMMENT '失败次数',
  `last_execute_result` VARCHAR(50) COMMENT '最后执行结果：SUCCESS-成功, FAILED-失败, RUNNING-运行中',
  `last_error_message` TEXT COMMENT '最后执行错误信息',
  `log_execution` TINYINT(1) DEFAULT 0 COMMENT '是否记录执行日志',
  `timeout_seconds` INT DEFAULT 0 COMMENT '超时时间（秒），0表示不限制',
  `retry_count` INT DEFAULT 0 COMMENT '重试次数',
  `retried_count` INT DEFAULT 0 COMMENT '已重试次数',
  `task_group` VARCHAR(100) COMMENT '任务分组',
  `priority` INT DEFAULT 3 COMMENT '优先级：1-高, 2-中, 3-低',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` VARCHAR(64) COMMENT '创建人',
  `updated_by` VARCHAR(64) COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_task_code` (`task_code`),
  KEY `idx_next_execute_time` (`next_execute_time`),
  KEY `idx_task_group` (`task_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='定时任务表';
